feat(roles/duplicity_backup): add status verb to backctl
This is useful for administrators to quickly check the backup state.

diff --git a/roles/duplicity_backup/templates/backctl b/roles/duplicity_backup/templates/backctl
--- a/roles/duplicity_backup/templates/backctl
+++ b/roles/duplicity_backup/templates/backctl
@@ -25,7 +25,7 @@ readonly PASSPHRASE="{{ lookup('ansible.builtin.password', 'secrets/backup_passp
 readonly VOLSIZE=1024
 
 show_usage() {
-  echo "Usage: $0 [-h] [-i <ID>] [-d <DIRECTORY>] [-e <FILES TO EXCLUDE>] [-v] <VERB: incremental, full_and_clear_all_incrementals, interactive_restore>" >&2
+  echo "Usage: $0 [-h] [-i <ID>] [-d <DIRECTORY>] [-e <FILES TO EXCLUDE>] [-v] <VERB: incremental, full_and_clear_all_incrementals, interactive_restore, status>" >&2
 }
 
 while getopts vi:d:e:h option; do
@@ -50,16 +50,16 @@ if [ -z "$ID" ]; then
   exit 1
 fi
 
-if [ -z "$DIRECTORY" ]; then
-  echo 'Missing directory to backup or restore parameter' >&2
-  show_usage
-  exit 1
-fi
-
 shift $((OPTIND - 1))
 
 if [ $# -lt 1 ]; then
   echo "Missing verb" >&2
+  show_usage
+  exit 1
+fi
+
+if [ "$1" != 'status' ] && [ -z "$DIRECTORY" ]; then
+  echo 'Missing directory to backup or restore parameter' >&2
   show_usage
   exit 1
 fi
@@ -125,6 +125,9 @@ case "$1" in
     do
       :
     done;;
+
+  status)
+    duplicity collection-status ${DUPLICITY_VERBOSE:+-vinfo} "$TARGET_URL";;
 
   *)
     echo "Unknown verb: $1" >&2
